/* ===== ATTENDANCE SHEETS: the paper route (owner, 29 Sep 2026) =====
   "I want 2 printable sheet generator from the attendance sheet, one for Shyam and one for Deepak aka Champai. The one
   for Shyam should be generated using his whatsapp text in mind, that way he can easily fill the same on a sheet and
   then he gives it to Deepak whose sheet is generated by how we enter data by hand on the app ... This gives us a
   verification route for the attendance and physical copy that I can file for every day for record keeping."

   Three documents for one day, printed through the one print view:
   - SHYAM'S SHEET, the supervisor's roll on paper: In time on the front (the 6 AM block, then the 8:30 AM shift by area
     in his order, numbered lines he writes names on, an EXTRA box per area, the absent by tier) and Out time on the
     back (who left at 5, then the later blocks with their area, EXTRA and the work done). Blank lines only (owner):
     he writes the names as he does on WhatsApp.
   - DEEPAK'S SHEET, the app's Staff → Day on paper: the active roster in the Day view's order, P / H / A, area, in, out,
     hours, OT, a few rows for anyone not on it, the EXTRA table, and the three signatures that make the route a check.
   - THE FILLED COPY: the same form carrying what was entered in the app for the day, to staple behind the two.
   Names come from the roster on this device; nothing about a worker is written into the build. */

var ATT_SHEET_IN_AREAS = [
  ['VAT A1', 6, true], ['VAT A2', 6, true], ['Barrel & pickling', 6, true], ['Pickling A1 & A2', 5, true], ['Office & gate', 4, false]
];
var _attSheetPick = { shyam: true, deepak: true, filled: true };

function _asHead(title, iso, right) {
  return '<div class="inv-as-head"><span class="inv-as-title">' + title + '</span>' +
    '<span class="inv-as-meta">' + escHtml(formatDate(iso) + ' · ' + attDayName(iso)) + (right ? ' · ' + right : '') + '</span></div>';
}
function _asHm(min) {
  if (min == null || isNaN(min)) return '';
  var h = Math.floor(min / 60), m = Math.round(min % 60);
  var ap = h >= 12 && h < 24 ? 'PM' : 'AM', h12 = h % 12 === 0 ? 12 : h % 12;
  return h12 + ':' + String(m).padStart(2, '0') + ' ' + ap;
}

// A block's "17:00" read the way the rest of the sheet writes a time.
function _asClock(t) {
  var m = /^(\d{1,2}):(\d{2})$/.exec(String(t || ''));
  return m ? _asHm(parseInt(m[1], 10) * 60 + parseInt(m[2], 10)) : String(t || '');
}

/* A line or field carrying what was recorded: printed in the ink colour of a filled form (inv-as-fill). */
function _asFillLines(texts, min, from) {
  var h = '', n = Math.max(min, texts.length);
  for (var i = 0; i < n; i++) {
    h += '<div class="inv-as-line">' + (from != null ? '<span class="inv-as-num">' + (from + i) + ')</span>' : '') +
      (texts[i] ? '<span class="inv-as-fill">' + escHtml(texts[i]) + '</span>' : '') + '</div>';
  }
  return h;
}
function _asFillField(label, value, after) {
  return '<div class="inv-as-field"><span>' + label + '</span><span class="inv-as-blank">' + (value ? '<span class="inv-as-fill">' + escHtml(value) + '</span>' : '') + '</span>' +
    (after ? '<span>' + after + '</span>' : '') + '</div>';
}
function _asName(id) { var w = staffById(id) || staffById(Number(id)); return w ? w.name : String(id); }
function _asBlockMin(t) { var m = /^(\d{1,2}):(\d{2})$/.exec(String(t || '')); return m ? +m[1] * 60 + +m[2] : null; }

/* Shyam's roll: In time (front) and Out time (back). Numbers run on within a slot, as he writes them. With `rec` (an
   earlier day the app holds; owner, 29 Sep 2026: "if we have previous day's data ... that should be printed when
   printing out Shyam's sheet for any previous day, that way giving them a tutorial becomes easy") the same sheet comes
   out filled in his own shape: names under their area, the absent by tier, each block's area, crew and EXTRA, who left
   at 5 and who later, with their own times. */
function attSheetShyamHtml(iso, rec) {
  var marks = rec ? rec.marks || {} : {}, extra = rec ? rec.extra || [] : [];
  var byBox = {}, absM = [], absW = [], flex = [];
  var boxOf = { 'vat-a1': 0, 'vat-a2': 1, 'barrel': 2, 'pickling-barrel': 2, 'pickling-vat': 3, 'office': 4, 'gate': 4 };
  Object.keys(marks).forEach(function(id) {
    var m = marks[id], w = staffById(id) || staffById(Number(id));
    if (!m || !m.st) return;
    if (m.st === 'A') { (w && w.comp === 'monthly' ? absM : absW).push(_asName(id)); return; }
    var b = boxOf[m.area || (w && w.area) || 'flex'];
    if (b == null) flex.push(_asName(id)); else (byBox[b] = byBox[b] || []).push(_asName(id));
  });
  var cover = {};
  extra.forEach(function(x) { if ((x.kind || 'coverage') === 'coverage') { var b = boxOf[x.area]; if (b != null) cover[b] = (cover[b] || 0) + (x.hours || 0); } });
  var blocks = extra.filter(function(x) { return x.kind === 'block'; }).sort(function(a, b) { return (_asBlockMin(a.from) || 0) - (_asBlockMin(b.from) || 0); });
  var morning = blocks.filter(function(x) { var f = _asBlockMin(x.from); return f != null && f < 510; });
  var evening = blocks.filter(function(x) { var f = _asBlockMin(x.from); return f == null || f >= 510; });

  var n = 1, boxes = '';
  ATT_SHEET_IN_AREAS.forEach(function(a, i) {
    var names = byBox[i] || [];
    boxes += '<div class="inv-as-box"><div class="inv-as-box-h">' + a[0] + '</div>' + _asFillLines(names, a[1], n) +
      (a[2] ? _asFillField('EXTRA', cover[i] ? formatNum(cover[i], 1).replace(/\.0$/, '') : '', 'hours') : '') + '</div>';
    n += Math.max(a[1], names.length);
  });
  if (flex.length) { boxes += '<div class="inv-as-box"><div class="inv-as-box-h">No line written</div>' + _asFillLines(flex, 1, n) + '</div>'; n += flex.length; }
  boxes += '<div class="inv-as-box"><div class="inv-as-box-h">Monthly absent</div>' + _asFillLines(absM, 3, n) +
    '<div class="inv-as-box-h">Weekly absent</div>' + _asFillLines(absW, 3, n + Math.max(3, absM.length)) + '</div>';
  var block = function(title, x, lines) {
    var area = x ? extraAreas(x).map(areaLabel).join(' + ') : '';
    var crew = x && Array.isArray(x.crew) ? x.crew.map(_asName) : [];
    return '<div class="inv-as-box"><div class="inv-as-box-h">' + title + '</div>' + _asFillField('Area', area) + _asFillLines(crew, lines, 1) +
      _asFillField('EXTRA', x && x.hours ? formatNum(x.hours, 1).replace(/\.0$/, '') : '', 'hours') + _asFillField('Work done', '') + '</div>';
  };
  var mBoxes = '';
  for (var k = 0; k < Math.max(2, morning.length); k++) mBoxes += block('Block ' + (k + 1) + (morning[k] ? ' · ' + _asClock(morning[k].from) + ' – ' + _asClock(morning[k].to) : ''), morning[k], 3);
  var worked = rec ? '<div class="inv-as-note">Filled from the app&rsquo;s record of this day, as a worked example.</div>' : '';
  var front = '<div class="inv-as-page" data-sheet="shyam-in"' + (rec ? ' data-filled' : '') + '>' + _asHead('In time', iso, 'Shyam') + worked +
    '<div class="inv-as-slot">6:00 AM</div><div class="inv-as-grid">' + mBoxes + '</div>' +
    '<div class="inv-as-slot">8:30 AM</div><div class="inv-as-grid">' + boxes + '</div>' +
    '<div class="inv-as-note">Write each name as on WhatsApp. EXTRA is the hours booked to the area for a hand short.</div></div>';

  // Out time: whoever is on no evening block leaves in the 5 PM list, with their own time when it is not 5.
  var onBlock = {};
  evening.forEach(function(x) { (x.crew || []).forEach(function(id) { onBlock[String(id)] = true; }); });
  var five = [];
  Object.keys(marks).forEach(function(id) {
    var m = marks[id];
    if (!m || (m.st !== 'P' && m.st !== 'H') || onBlock[String(id)]) return;
    five.push(_asName(id) + (m.outMin != null && m.outMin !== 1020 ? ' ' + _asHm(m.outMin) : ''));
  });
  var fiveA = five.slice(0, Math.max(8, Math.ceil(five.length / 2))), fiveB = five.slice(fiveA.length);
  var later = function(x) {
    var area = x ? extraAreas(x).map(areaLabel).join(' + ') : '';
    var crew = x && Array.isArray(x.crew) ? x.crew.map(_asName) : [];
    return '<div class="inv-as-box"><div class="inv-as-box-h">Out at ' + (x && x.to ? '<span class="inv-as-fill">' + escHtml(_asClock(x.to)) + '</span>' +
      (x.from ? ' <span class="inv-as-num">from ' + escHtml(_asClock(x.from)) + '</span>' : '') : '____________') + '</div>' +
      _asFillField('Area', area) + _asFillLines(crew, 5, 1) +
      _asFillField('EXTRA', x && x.hours ? formatNum(x.hours, 1).replace(/\.0$/, '') : '', 'hours') + _asFillField('Work done', '') + '</div>';
  };
  var lBoxes = '';
  for (var j = 0; j < Math.max(4, evening.length); j++) lBoxes += later(evening[j]);
  var back = '<div class="inv-as-page" data-sheet="shyam-out"' + (rec ? ' data-filled' : '') + '>' + _asHead('Out time', iso, 'Shyam') + worked +
    '<div class="inv-as-slot">5:00 PM</div><div class="inv-as-grid"><div class="inv-as-box">' + _asFillLines(fiveA, 8, 1) + '</div>' +
    '<div class="inv-as-box">' + _asFillLines(fiveB, 8, Math.max(8, fiveA.length) + 1) + '</div></div>' +
    '<div class="inv-as-slot">Later</div><div class="inv-as-grid">' + lBoxes + '</div>' +
    '<div class="inv-as-sign"><div>Filled by Shyam</div><div>Sent on WhatsApp at</div><div>Handed to Deepak at</div></div></div>';
  return front + back;
}

// An earlier day the app holds is printed filled on Shyam's sheet; today and any day with nothing recorded, blank.
function attSheetFillFor(iso) {
  var rec = attDay(iso, false);
  return rec && iso < localDateStr() && Object.keys(rec.marks || {}).length ? rec : null;
}

/* The roster in the Day view's order, and anyone marked that day who has since left it. */
function _asRoster(rec) {
  var list = staffActive().slice();
  if (rec) Object.keys(rec.marks || {}).forEach(function(id) {
    if (!list.some(function(w) { return String(w.id) === String(id); })) { var w = staffById(id) || staffById(Number(id)); if (w) list.push(w); }
  });
  return list;
}

/* Deepak's sheet: blank, or filled with what the app holds for the day. */
function attSheetDeepakHtml(iso, filled) {
  var rec = filled ? attDay(iso, false) : null;
  var roster = _asRoster(rec);
  var rows = roster.map(function(w, i) {
    var m = rec && rec.marks ? rec.marks[w.id] : null;
    var st = m ? m.st : '';
    var tick = function(k) { return '<td class="inv-as-tick">' + (st === k ? k : '') + '</td>'; };
    return '<tr><td class="inv-as-tick">' + (i + 1) + '</td><td>' + escHtml(w.name || '') + '</td>' +
      '<td class="inv-as-tick">' + (compIsHourly(w) ? 'H' : w.comp === 'monthly' ? 'M' : 'D') + '</td>' +
      tick('P') + tick('H') + tick('A') +
      '<td>' + (m && m.st !== 'A' ? escHtml(areaLabel(m.area || w.area || 'flex')) : '') + '</td>' +
      '<td>' + (m ? escHtml(_asHm(m.inMin)) : '') + '</td><td>' + (m ? escHtml(_asHm(m.outMin)) : '') + '</td>' +
      '<td>' + (m && m.hours ? escHtml(formatNum(m.hours, 1)) : '') + '</td><td>' + (m && m.ot ? escHtml(formatNum(m.ot, 1)) : '') + '</td></tr>';
  }).join('');
  if (!filled) for (var k = 0; k < 3; k++) rows += '<tr><td class="inv-as-tick">' + (roster.length + k + 1) + '</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>';

  var extras = rec ? (rec.extra || []) : [];
  var exRows = extras.map(function(x) {
    var crew = (Array.isArray(x.crew) ? x.crew : []).map(function(id) { var w = staffById(id); return w ? w.name : ''; }).filter(Boolean).join(', ');
    return '<tr><td>' + escHtml(areaLabel(x.area || 'flex')) + '</td><td>' + escHtml(_asClock(x.from)) + '</td><td>' + escHtml(_asClock(x.to)) + '</td>' +
      '<td>' + escHtml(crew) + '</td><td>' + (x.hours ? escHtml(formatNum(x.hours, 1)) : '') + '</td></tr>';
  }).join('');
  if (!filled || !extras.length) for (var j = 0; j < (filled ? 1 : 4); j++) exRows += '<tr><td></td><td></td><td></td><td></td><td></td></tr>';

  var title = filled ? 'Attendance as entered in the app' : 'Attendance entry';
  return '<div class="inv-as-page" data-sheet="' + (filled ? 'filled' : 'deepak') + '">' + _asHead(title, iso, filled ? '' : 'Deepak') +
    (filled && !rec ? '<div class="inv-as-note">Nothing is entered in the app for this day yet.</div>' : '') +
    '<table class="inv-as-table"><thead><tr><th class="inv-as-tick">#</th><th>Worker</th><th class="inv-as-tick">Tier</th>' +
    '<th class="inv-as-tick">P</th><th class="inv-as-tick">H</th><th class="inv-as-tick">A</th><th>Area</th><th>In</th><th>Out</th><th>Hours</th><th>OT</th></tr></thead>' +
    '<tbody>' + rows + '</tbody></table>' +
    '<div class="inv-as-slot">EXTRA</div>' +
    '<table class="inv-as-table"><thead><tr><th>Area</th><th>From</th><th>To</th><th>Crew</th><th>Hours</th></tr></thead><tbody>' + exRows + '</tbody></table>' +
    '<div class="inv-as-note">Tier: M monthly, H hourly, D daily. P present, H half day, A absent. Hours for an hourly hand; OT for the rest.</div>' +
    (filled
      ? '<div class="inv-as-note">Printed from the app ' + escHtml(formatTimestamp(Date.now())) + '. Staple behind Shyam\'s and Deepak\'s sheets for the day.</div>'
      : '<div class="inv-as-sign"><div>Filled by Shyam</div><div>Checked by Deepak</div><div>Entered in the app by / on</div></div>') +
    '</div>';
}

/* Staff → Day → Print sheets: which of the three, then the preview. */
function attSheetOpen() {
  var rec = attDay(_attDate, false);
  var c = function(k, label, sub, off) {
    return '<label class="inv-field-check"><input type="checkbox" class="inv-check" data-as-pick="' + k + '"' + (_attSheetPick[k] && !off ? ' checked' : '') + (off ? ' disabled' : '') + '> ' +
      label + (sub ? ' <span class="inv-note">' + sub + '</span>' : '') + '</label>';
  };
  dialogOpen('<div class="inv-dialog">' + dialogHeadHtml('Print sheets · ' + escHtml(formatDate(_attDate))) +
    '<div class="inv-field">' +
    c('shyam', 'Shyam\'s sheet', attSheetFillFor(_attDate) ? 'In time and Out time, filled with this day\'s record as a worked example (2 pages)' : 'In time and Out time, as his WhatsApp roll (2 pages)') +
    c('deepak', 'Deepak\'s sheet', 'the Day entry: the roster, P / H / A, area, in, out, hours, OT, EXTRA') +
    c('filled', 'Filled copy', rec ? 'what the app holds for this day' : 'nothing entered for this day yet', !rec) +
    '</div><div class="inv-dialog-foot"><button class="inv-btn inv-btn-secondary" data-action="invCloseOverlay">Cancel</button>' +
    '<button class="inv-btn inv-btn-primary" data-action="invAttSheetPreview">Preview</button></div></div>', { dismiss: true });
}

function attSheetPreview() {
  document.querySelectorAll('[data-as-pick]').forEach(function(el) { if (!el.disabled) _attSheetPick[el.dataset.asPick] = el.checked; });
  var rec = attDay(_attDate, false);
  var h = (_attSheetPick.shyam ? attSheetShyamHtml(_attDate, attSheetFillFor(_attDate)) : '') + (_attSheetPick.deepak ? attSheetDeepakHtml(_attDate, false) : '') +
    (_attSheetPick.filled && rec ? attSheetDeepakHtml(_attDate, true) : '');
  if (!h) { showToast('Pick at least one sheet', 'error'); return; }
  closeOverlay();
  document.getElementById('invPrintBody').innerHTML = h;
  document.getElementById('invPrintView').classList.add('inv-print-view-active');
  _printInvId = null;
  printFit();
  document.body.style.overflow = 'hidden';
  document._savedTitle = document.title;
  document.title = 'Attendance ' + _attDate;
}
